### ISSUE TITLE
Test files are not type-checked: tsconfig.test.json includes only 4 of 32

### ISSUE THREAD

**Issue by mixja** [jmenga/effect-dynamodb#106]
### Version

`effect-dynamodb` 1.15.0

### Summary

`pnpm check` type-checks four test files. The other 28 are never compiled, so test code can reference options that do not exist, and does.

`packages/effect-dynamodb/tsconfig.test.json`:

```json
"include": [
  "src",
  "test/Entity.types.test.ts",
  "test/Aggregate.types.test.ts",
  "test/PureAuthoring.types.test.ts",
  "test/VectorSearch.types.test.ts"
]
```

Vitest transpiles without checking types, so nothing else catches it either.

### How it surfaced

`test/Aggregate.timestamps.test.ts` carried this in two places:

```ts
players: Aggregate.many("players", { entityType: "MatchPlayer", composite: ["playerId"] })
```

`composite` is not a property of `ManyEdgeConfig` — the real option is `sk: { composite: [...] }`. Compiled on its own it fails as expected:

```
error TS2769: No overload matches this call.
  Object literal may only specify known properties, and 'composite' does not exist
  in type 'ManyEdgeConfig<RefEntity<Top, unknown>>'.
```

The author was reaching for the sort-key option from #103. It silently did nothing, and the fixture asserted against mocked writes that real DynamoDB rejects. Fixed in the #103 branch, but only because a runtime guard surfaced it — the type system should have.

### Why it matters beyond that one line

Tests are where the public API's ergonomics get exercised first. An option name that type-checks in a test but not in user code is a false signal about the API surface, and a fixture that cannot compile is a fixture nobody can trust as documentation of intended usage.

### Suggested fix

Widen the include to `test`:

```json
"include": ["src", "test"]
```

Expect fallout — this is the first compile for 28 files. Likely categories:

- options that do not exist on their config objects (as above)
- mock `DynamoClient` layers missing newer methods, or with loose signatures
- `as any` / untyped `mock.calls[0][0]` access that trips `noUncheckedIndexedAccess`
- fixtures relying on inference that `exactOptionalPropertyTypes` rejects

Worth doing as its own PR precisely because the fallout is unknown until the include is widened. If the volume is large, an intermediate step is to add files to the include in batches rather than carry a long-lived `// @ts-expect-error` set.

### Affected

- `packages/effect-dynamodb/tsconfig.test.json`
- likely siblings: `packages/schema`, `packages/effect-dynamodb-geo`, `packages/language-service` — each should be checked for the same narrowing

**Comment by jmenga** [comment]
Concrete data on the fallout, from the #102 branch.

`connected.test.ts` is one of the excluded files. Compiled under a temporary tsconfig it has **3 pre-existing type errors**:

- ~line 1839 — `Effect<void, unknown, unknown>` not assignable to `Effect<void, unknown, Scope>` under `exactOptionalPropertyTypes`
- ~line 5106 — possibly-undefined invocation
- ~line 7022 — EventStore `EventStream` `this`-context variance (`LedgerState` vs `never`)

So adding just that one file to the include needs those three fixed first. That supports doing this in batches rather than one big include change — and the third one is worth a look on its own, since a `this`-context variance failure on `EventStream` may indicate the generic is under-constrained in the public API, not just in the test.

Separately, the mock `DynamoClientService` layers in several test files (`Transaction.test.ts`, `Batch.test.ts`, `DynamoClient.test.ts`) are missing methods the service now declares — `searchVectors`, `updateTable`, `listTables`, `createBackup` and ~13 more. That is a large but mechanical category: a shared test-layer helper providing `Effect.die("not used")` defaults for every method would fix all of them at once and stop the drift recurring.
